### ISSUE TITLE
Dataloader issue

### ISSUE THREAD

**Issue by DamianMYM** [NIRVANALAN/LN3Diff#10]
Hi Yushi,

Today I am trying to run `bash shell_scripts/final_release/train/stage-1-vae/Objaverse/mv-75k-addDepth_demo.sh`, I met the following errors:

1. **TypeError: load_data() got an unexpected keyword argument 'compile'**.  Yes, I pasted these args from defaults. 

2. And then, after the second run, fixed the first one but  I met :
 ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/test/anaconda3/envs/hoidm/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/test/anaconda3/envs/hoidm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/test/anaconda3/envs/hoidm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/test/mym4t/_mym/github_lib/LN3Diff/datasets/g_buffer_objaverse.py", line 901, in __getitem__
    data = self._read_data(idx)
  File "/media/test/mym4t/_mym/github_lib/LN3Diff/datasets/g_buffer_objaverse.py", line 1020, in _read_data
    bbox = self.load_bbox(depth > 0)
  **File "/media/test/mym4t/_mym/github_lib/LN3Diff/datasets/g_buffer_objaverse.py", line 894, in load_bbox
    height, width = nonzero_value.max(dim=0)[0]
ValueError: too many values to unpack (expected 2)**

3. I tried some ways to avoid this error, but you know the troubles always follow. 

So would you please help me with those issues? 

Many thanks, 
Damian

**Comment by NIRVANALAN** [comment]
Hi Damian, 

Actually I have not well polished the training code, so the data loading pipeline might be a little bit messy. May I ask whether you are training the VAE and diffusion? I can focus on polishing that part first.

Thanks and looking forward to your reply.

**Comment by DamianMYM** [comment]
Hi Yushi, 

I tired to use your env to run again, by  doing this ` batch.pop('caption')  # not required
        #batch.pop('nv_caption')  # not required
        batch.pop('ins')  # not required
        #batch.pop('nv_ins')  # not required`  
        And then, the error is 
`  File "/home/test/_zjun/LN3Diff/nsr/train_nv_util.py", line 1298, in forward_backward
    nv_c = th.cat([micro['nv_c'], micro['c']])
KeyError: 'nv_c'`
This is so weird.

You see, my plan is to use my own dataset to train your model and see if we can have a better result, but now...

Anyway, I hope you can polish the training code very soon. 

Thank you!

**Comment by NIRVANALAN** [comment]
Sure, I will polish the code asap. So which script are you running now, for VAE training right?

**Comment by DamianMYM** [comment]
Specifically, I used the script below and selected the relevant codes only for VAE training, but I would like to run your script successfully first. 
`shell_scripts/final_release/train/stage-1-vae/Objaverse/mv-75k-addDepth_disc.sh`

I appreciate your quick reply.

**Comment by DamianMYM** [comment]
Hi Yushi, 

I am writing to seek your guidance on a few questions regarding your work with the Objaverse dataset.

Firstly, I noticed that there are several rendering options during the training process of the Objaverse dataset. Could you please clarify whether this rendering step is part of the differentiable rendering included in the training process? Additionally, I would appreciate it if you could explain the purpose of this section of the code, as I have studied your paper but would like a deeper understanding.

Moreover, I observed that the data loader packages multi-view images, rendered depth maps, and Plücker coordinates for the MVEncoder. Am I correct in understanding that I only need to prepare these three types of data for the encoder? **If my dataset does not provide the computed Plücker coordinates, what should I do?**

Thank you very much for your time and assistance. I look forward to your valuable insights.

Damian

**Comment by NIRVANALAN** [comment]
Hi, thanks for your message. I will polish the stage-1 VAE training code/data this weekend, and get back to you asap. Regarding the data input, the Plucker can be computed from the camera c, which is necessary if you need to train the VAE yourself. 

For the rendering part, the rendering options is for different dataset. For FFHQ/ShapeNet, the camera parameters are different with G-Objaverse. For your case, I guess you need to set your own rendering options to match the camera parameter of your dataset.

Yushi.

**Comment by DamianMYM** [comment]
Hi Yushi, 

I hope you are doing well. I wanted to follow up on the update you mentioned last week regarding the training code release.  I was wondering if you could provide an update on the expected timeline for the release. 

Your work is greatly appreciated, and I’m looking forward to the news.

Best,
Damian

**Comment by NIRVANALAN** [comment]
Hi Damian, I am working on it and will post a trainable VAE script perhaps tomorrow. Will keep you updated.

**Comment by NIRVANALAN** [comment]
Hi Damian, I have updated the stage-1 VAE training script as requested. Please check the latest commit. The script is at ```shell_scripts/final_release/train/stage-1-vae/Objaverse/ln3diff-vae-175K_debug.sh```, and I have also put a demo training data in the ./assets, as denoted in the $data_dir in the script file. To train the VAE on G-Objaverse, you can download my pre-processed data from Onedrive (the link is in the readme), or you can process you data into the same format as my version (I chunk the multi-view inputs together just for IO efficiency). To train the VAE, you can tune the $patch_rendering_resolution and $batch_size according to the VRAM you have.

Please let me know if there is anything I can help. I will also update the readme afterwards.

**Comment by DamianMYM** [comment]
Hi Yushi,
  
Thank you for your hard work! I tried your demo earlier today, and I’m glad to see it works.
  
I have a question regarding training on my dataset. Currently, I have only **four views** for each frame. I would like to know if four views are sufficient for predicting **novel view**. Before your recent code update, I primarily focused on adjusting this part of the code (cropped_target), but I consistently encountered errors due to tensor mismatches. I will try using your updated code next to see if the errors persist.

I also noticed that you set up some new arguments, including use_chunk, num_frame and others. It seems that num_frame needs to be greater than four and must be twice the value of micro_batch. Could you please explain why using five frames does not work in the demo, while six frames do (with the micro_batch adjusted accordingly)?
  
Additionally, I would like to know if you have been using a batch_size of 4 for training in practice(or maybe try a bigger batch_size).
  
Thank you very much for your time and assistance. I look forward to your insights.
  
 Best,
 Damian

**Comment by NIRVANALAN** [comment]
Hi Damian,

Thanks for your message. Regarding the input views, 4 views shall be fine but more views are encouraged. Actually my first version uses 4 views.

The new arguments are used for loading my chunked dataset, where I load 2*6 views together and they naturally serve batch=2.

Batch=4 is totally fine, but this would require a longer time to converge. Just tune the batch size and cropped_target (patch size) to balance it.

**Comment by DamianMYM** [comment]
Thanks for your quick response.  I also wanna know if albedo is necessary for the input.  My dataset only contains four-views RGB images, depth and camera intrinsic parameters.

**Comment by NIRVANALAN** [comment]
Hi, I did not use albedo in my input, but adding normal shall be helpful. RGB and Depth alone shall be enough in most cases.

**Comment by DamianMYM** [comment]
Hi Yushi,
 
Thanks for your prompt and patient reply, I shall close this issue.

Best,
Damian
