### ISSUE TITLE
CUDA error when running t23D inference

### ISSUE THREAD

**Issue by XYkong-CS** [NIRVANALAN/LN3Diff#11]
Thanks for your great job!
I am running the t23d inference of Obajverse, but met a weird problem at:
"        to_torch = partial(torch.tensor, dtype=torch.float32, device=device)
        sigmas = to_torch((1 - alphas_cumprod) / alphas_cumprod) ** 0.5"
 in "LN3Diff/sgm/modules/diffusionmodules/discretizer.py":

Error log:
Initialized embedder #0: FrozenCLIPEmbedder with 123060480 params. Trainable: False
sampling...
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [32,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [33,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [34,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [35,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [36,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [37,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [38,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [39,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [40,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [41,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [42,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [43,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [44,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [45,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [46,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [47,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [48,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [49,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [50,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [51,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [52,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [53,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [54,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [55,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [56,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [77,0,0], thread: [57,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [70,0,0], thread: [58,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [70,0,0], thread: [59,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [70,0,0], thread: [60,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [70,0,0], thread: [61,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [70,0,0], thread: [62,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [70,0,0], thread: [63,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

And I have tried to find the cause of it, and found it is due to the operation of putting the data to gpu (device=cuda:0).
But at the moment the memory-usage is  16359MiB / 24564MiB.
So I wonder is it the cuda environment problem or out of memory problem? Could you conveniently tell me how much GPU memory is occupied during your inference?

**Comment by NIRVANALAN** [comment]
Hi, thanks for your interest. I guess this is not due to GPU OOM issue, but some operations regarding indexing a Tensor with over-large index. Usually the inference causes around 16GB, so your GPU shall be totally fine. Would you elaborate more which script you run so that I can help reproduce this bug?

**Comment by XYkong-CS** [comment]
Thanks for your reply! I ran "shell_scripts/final_release/inference/sample_obajverse_t23d_dit.sh" with the default setting except for replacing "--resume_checkpoint ./checkpoints/objaverse/objaverse-dit/t23d/model_joint_denoise_rec_model3910000.safetensors \" with "--resume_checkpoint checkpoints/objaverse/objaverse-dit/t23d/model_joint_denoise_rec_model3820000.pt" for using the downloaded ckpt.

With conda environment:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.1.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antialiased-cnns          0.3                      pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.6.2.post1              pypi_0    pypi
apex                      0.1                      pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
beartype                  0.19.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blobfile                  3.0.0                    pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
ca-certificates           2024.9.24            h06a4308_0
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
clip                      1.0                      pypi_0    pypi
cmake                     3.25.0                   pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
diffusers                 0.30.3                   pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
fastapi                   0.115.2                  pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.10.0                pypi_0    pypi
ftfy                      6.3.0                    pypi_0    pypi
gdown                     4.4.0                    pypi_0    pypi
gradio                    4.44.1                   pypi_0    pypi
gradio-client             1.3.0                    pypi_0    pypi
grpcio                    1.67.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.6                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.26.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.36.0                   pypi_0    pypi
imageio-ffmpeg            0.5.1                    pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
kiui                      0.2.14                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
kornia                    0.7.3                    pypi_0    pypi
kornia-rs                 0.1.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
lightning-utilities       0.11.8                   pypi_0    pypi
lit                       15.0.7                   pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
lmdb                      1.5.1                    pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
lxml                      5.3.0                    pypi_0    pypi
lz4                       4.3.3                    pypi_0    pypi
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
networkx                  3.2.1                    pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
objprint                  0.2.3                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
onnxruntime               1.19.2                   pypi_0    pypi
open-clip-torch           2.27.1                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openexr                   3.3.1                    pypi_0    pypi
openssl                   3.0.15               h5eee18b_0
orjson                    3.10.9                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       24.2             py39h06a4308_0
platformdirs              4.3.6                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
propcache                 0.2.0                    pypi_0    pypi
protobuf                  5.28.2                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
pycryptodomex             3.21.0                   pypi_0    pypi
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pymatting                 1.1.12                   pypi_0    pypi
pymcubes                  0.1.6                    pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pyre-extensions           0.0.23                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.9.20               he870216_1
python-dateutil           2.9.0.post0              pypi_0    pypi
python-multipart          0.0.12                   pypi_0    pypi
pytorch-lightning         2.2.1                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
referencing               0.35.1                   pypi_0    pypi
regex                     2024.9.11                pypi_0    pypi
rembg                     2.0.59                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.9.2                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
ruff                      0.7.0                    pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                75.1.0           py39h06a4308_0
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0
starlette                 0.40.0                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
timm                      1.0.11                   pypi_0    pypi
tk                        8.6.14               h39e8969_0
tokenizers                0.20.1                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.1.0+cu118              pypi_0    pypi
torchaudio                2.1.0+cu118              pypi_0    pypi
torchdiffeq               0.2.4                    pypi_0    pypi
torchmetrics              1.5.0                    pypi_0    pypi
torchvision               0.16.0+cu118             pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.45.2                   pypi_0    pypi
trimesh                   4.5.0                    pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typer                     0.12.5                   pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
uvicorn                   0.32.0                   pypi_0    pypi
varname                   0.13.5                   pypi_0    pypi
vision-aided-loss         0.1.0                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webdataset                0.2.100                  pypi_0    pypi
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.44.0           py39h06a4308_0
xformers                  0.0.22.post4+cu118          pypi_0    pypi
xz                        5.4.6                h5eee18b_1
yarl                      1.15.5                   pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1

And nvcc:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

I found "torch.tensor((1 - alphas_cumprod) / alphas_cumprod, dtype=torch.float32)" could work but failed as long as adding (device=device) when device=cuda:0 (while device=cpu is OK).
I also have tried different version of torch (2.0.0 as your default setting) but still have the same error.

**Comment by XYkong-CS** [comment]
Now the error is updated...
"

../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [113,0,0], thread: [92,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [113,0,0], thread: [93,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [113,0,0], thread: [94,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [113,0,0], thread: [95,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/3D/LN3Diff/scripts/vit_triplane_diffusion_sample_objaverse.py", line 346, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/3D/LN3Diff/scripts/vit_triplane_diffusion_sample_objaverse.py", line 233, in main
[rank0]:     training_loop_class.eval_cldm(
[rank0]:   File "/home/miniconda3/envs/ln3diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/3D/LN3Diff/./nsr/lsgm/sgm_DiffusionEngine.py", line 480, in eval_cldm
[rank0]:     samples = self.sample(c,
[rank0]:   File "/home/miniconda3/envs/ln3diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/3D/LN3Diff/./nsr/lsgm/sgm_DiffusionEngine.py", line 399, in sample
[rank0]:     randn = randn[idx_to_render]
"
So i printed the shape and index here
"
        if idx_to_render is not None:
            print("-----", randn.shape, idx_to_render)
            randn = randn[idx_to_render]
"
and got "----- torch.Size([4, 12, 32, 32]) [20 19 18 31 26 25 22]"

It seems its really because out of index error but i have no idea how idx_to_render get in this way...

**Comment by NIRVANALAN** [comment]
Interesting, thanks for the update. let me check the code and get back to you.

**Comment by XYkong-CS** [comment]
Thanks, waiting for your good news!
Also, I ran the i23d script successfully which means environment is OK. But there is a small problem that even if all 4x4 samples are generated, the script will continue to generate in a loop without stopping. But this should only be a minor problem with the logic of the loop statement, hopefully it will help you polish the code a bit!

**Comment by XYkong-CS** [comment]
Hi! I have found that:

"
        prompts_and_seed_to_render = {
            'The Eiffel tower.': np.array([20, 19, 18, 31, 26, 25, 22]),  # 0-3
            'a stone water well with a wooden shed.': np.array([7, 9, 15, 19, 23, 24, 28]),
            'A wooden chest with golden trim': np.array([3, 5, 6, 7]), 
            'A plate of sushi.': np.array([0, 3, 7, 11, 16]), 
            'A blue platic chair': np.array([0, 1, 2, 3]),
        }
" in vit_triplane_diffusion_sample_objaverse.py causes the out_of_index, except " 'A blue platic chair': np.array([0, 1, 2, 3])" can run successfully since seeds of it are smaller than 4.

**Comment by NIRVANALAN** [comment]
Thanks for your update, I will fix this bug later. Please let me know if there are any issues I can help later.
