### ISSUE TITLE
text 23d 's cfg_scale seems not work

### ISSUE THREAD

**Issue by MaxtirError** [NIRVANALAN/LN3Diff#12]
Thanks for you nice work. I have a problem about using unconditional guidance scale in text23d task of your works.

refer to the scritps `sample_obajverse_t23d_dit.sh`, we have the config of `unconditional_guidance_scale=6.5`, combining the trainer_name sgm_legacy and vit_triplane_diffusion_sample_objaverse, we found that the code use this variable in `scripts/vit_triplane_diffusion_sample_objaverse.py` line 235 `training_loop_class.eval_cldm()`.

And this functioni is in the scripts `nsr/lsgm/sgm_DiffusionEngine.py` , class DiffusionEngineLSGM. However, it's easy to find that in eval_cldm(), the args `unconditional_guidance_scale` is not been used.

I wonder :
1. Does this work support text23d  confidance free guidance?
2. Where is the real interface that I can use it .

More Information
I found a similar function in the image_cond based framework, the class 'FlowMatchingEngine', I notice that the function sample support `cfg_sclae` while the class `DiffusionEngineLSGM`'s sample function doesn't.

**Comment by NIRVANALAN** [comment]
Hi, thanks for your interest in our work.

1. The text23d pipeline supports CFG. I modified the whole training / inference pipeline from stable diffusion, and the CFG is configured directly in the config file (https://github.com/NIRVANALAN/LN3Diff/blob/a54dc7c087e4e222816dfeb22acb0f589644c86f/nsr/lsgm/sgm_DiffusionEngine.py#L156), which is here. https://github.com/NIRVANALAN/LN3Diff/blob/a54dc7c087e4e222816dfeb22acb0f589644c86f/sgm/configs/txt2img-clipl-compat.yaml#L60 Apologize for not polishing the code so well, and I will update accordingly. For I23D, the CFG value can be directly set in the bash file.
2. For I23D training, I switched from pure latent DDPM training (DiffusionEngineLSGM) to the flow matching trainer, which is the class "FlowMatchingEngine". They serve as the same function, and you can use the later if you need to train the model from scratch. FM's loss curve is more stable and converges faster compared to the conventional DDPM training, as I observed in this task.

Please keep me updated if there are any issues I can help with.

**Comment by MaxtirError** [comment]
Thanks for your kind reply! Now I understand this problem.

I meet another porblem when I running the VAE reconstruction code following the README.md, the scripts
`bash shell_scripts/final_release/inference/sample_obajverse.sh`.

At first, I just directly run this script. It gave me two bugs:

1. `idx_to_render` at script `scripts/vit_triplane_diffusion_sample_objaverse.py` line 248, it is not a varaiable of function eval_cldm in the context

2. `mesh_dump_path` reference before assignment at script `nsr/train_util_diffusion.py` at line 377

for the former I just commont out this line, for the latter I assign mesh_dump_path=None

Then I got a pretty confusing results at logs dir, like:

![截屏2024-11-10 00 18 12](https://github.com/user-attachments/assets/802730a1-533f-4dd3-9048-81d855631c57)


And the video have nothing but white and black.

I'd apperciate if you could give me some adivce about how to use the vae.

**Comment by NIRVANALAN** [comment]
Hi, thanks for your message. I just found out the path of shell script for stage-1 VAE is wrong, it should be ```bash shell_scripts/final_release/inference/vae_xl_reconstruction.sh```. I have just updated the readme, and please let me know if it works.

BTW, looks like the old script is for T23D. I have also fixed the ```idx_to_render``` bug for t23d. It originally serves for inferring specific random seeds.

**Comment by MaxtirError** [comment]
Thanks very much, I'll check the code.

Another question is about the triplane render. I generate a image-to-3d results. I trying to render a video with my custom camera setting. The setting is like preserve the intrinsics in "objv_eval_pose.pt", and change the camera extrinsics.

when I set camera with setting r=2, pitch=30, the results is quite nice.

https://github.com/user-attachments/assets/672eb9f2-7938-47fc-bf2c-18ee4b5f1c07



However, when I try r=3, the quality of image seems droped. Is that normal?
![image](https://github.com/user-attachments/assets/f7501558-213f-4ebb-a047-89c88e92d5c1)

**Comment by NIRVANALAN** [comment]
Hi, that's quite interesting since I have not zoomed out the camera for that much (The g-buffer dataset radius range should be in [1.5, 2].). The triplane rendering pipeline is borrowed from EG3D, and I have not changed too much. Looks like there is a strong aliasing artifacts, but volume rendering should not have such effects from my experience. Please keep me updated if you found out the solution.
