### ISSUE TITLE
Question about downloading the checkpoint

### ISSUE THREAD

**Issue by Au-LiuJY** [NIRVANALAN/LN3Diff#3]
As mentioned in the Readme,where can I download the model_joint_denoise_rec_model3820000.pt or model_joint_denoise_rec_model2990000.pt 
<img width="659" alt="image" src="https://github.com/user-attachments/assets/5ab5a58b-7119-48a9-b618-a3491da6111f">

**Comment by NIRVANALAN** [comment]
Hi, thanks for your interested in our work, it can be downloaded from the [Onedrive](https://entuedu-my.sharepoint.com/:f:/g/personal/yushi001_e_ntu_edu_sg/ErdRV9hCYvlBioObT1v_LZ4Bnwye3sv6p5qiVZPNhI9coQ?e=YpJ3jz). I will update the readme accordingly.

**Comment by Au-LiuJY** [comment]
> Hi, thanks for your interested in our work, it can be downloaded from the [Onedrive](https://entuedu-my.sharepoint.com/:f:/g/personal/yushi001_e_ntu_edu_sg/ErdRV9hCYvlBioObT1v_LZ4Bnwye3sv6p5qiVZPNhI9coQ?e=YpJ3jz). I will update the readme accordingly.

OK,thank you！

**Comment by Au-LiuJY** [comment]
Besides,when I run the `bash shell_scripts/final_release/inference/sample_obajverse_i23d_dit.sh`,some errors occur: RuntimeError: "upsample_bicubic2d_out_frame" not implemented for 'BFloat16',
Followings are my work steps:
I config
I use the demo image"teasure_chest-input.png",and resize it to (504,504),because the following setting is to devide it into 3 pieces.(The original size is (505,505))
![image](https://github.com/user-attachments/assets/1dcb9451-a0ea-47f5-82ce-2e30435ae2c4)
And in the "/LN3Diff/./sgm/modules/encoders/modules.py", the function of "encode_with_vision_transformer",
<img width="410" alt="image" src="https://github.com/user-attachments/assets/a4750546-3b0d-4c91-9017-737c1565a2ed">
it will raise an assert error,because the value of self.max_crops is 0 while the image.shape is "torch.Size([1, 6, 4, 252, 252])",
after it I have deleted this line of code“assert self.max_crops == img.shape[1]”，it finally raises "RuntimeError: "upsample_bicubic2d_out_frame" not implemented for 'BFloat16'"

Can you please give me some advice on it?Thanks in advance!
