### ISSUE TITLE
ShapeNet for training issue

### ISSUE THREAD

**Issue by DamianMYM** [NIRVANALAN/LN3Diff#5]
Dear author,

Thanks for your great work!

I encountered issues when I tried to train stage one VAE on ShapeNet.

First, the LMDB format dataset I downloaded from the provided link can NOT be unzipped. So I also downloaded the rendering ones and found only two categories(car and chair). And then I realised you haven't uploaded the eval dataset(as the training script requires args eval_data_dir). So could you please instruct me on what I should do? 

I just want to make sure that I was using the right script for training on Shapenet, which is vit_triplane_cvD_train.py. Is it the correct one?

Looking forward to seeing your reply!

Many thanks!
Damian

**Comment by NIRVANALAN** [comment]
Hi! Thanks for your message, I am looking into the dataset file I have uploaded and will get back to you ASAP.

**Comment by NIRVANALAN** [comment]
Hi Damian,

The LMDB [link](https://entuedu-my.sharepoint.com/:f:/g/personal/yushi001_e_ntu_edu_sg/EijBXIC_bUNOo0L3wnJKRqoBCqVnhhT_BReYRc1tc_0lrA?e=VQwWOZ) should be fine and does not need unzip, you can directly use them in the trinaing.

Regarding the training script, please check "scripts/vit_triplane_train.py" script for ShapeNet VAE training. I have not cleaned the training script (will do after it soon), but it shall be fine to check and run the script if you need it.

Please feel free to let me know if there are any issues.

**Comment by DamianMYM** [comment]
Hi,

Thank you for your response in the Mid-Autumn Festival, and I wish you happy.

I did used the provided link separately to download the LMDB dataset, and it looks fine. 

What about the arg --eval_data_dir? Train with 3 categories(chair, plane and car) and maybe try ffhq for evaluation?

**Comment by NIRVANALAN** [comment]
Hi, you can set eval_data_dir to the same path as train_data_dir to run the code. Just use the training set for diffusion training is fine, or you can train the whole shapenet dataset which still has very limited size.

**Comment by DamianMYM** [comment]
Unfortunately, idk if you've tested scripts/vit_triplane_train.py for Shapenet, it doesn't work directly due to some args issues, such as, got unexcepted args  --use_wds. Or if I delete this arg and use the same dir as training dir in eval dir, and I got the path error.

and which trainer I should choose?

**Comment by NIRVANALAN** [comment]
Hi, I am cleaning the training script recently and will release a better version soon. The wds dataset is not used when training ShapeNet, and you can ignore that args. I will update a training bash script soon here for VAE training on ShapeNet.

**Comment by DamianMYM** [comment]
Thanks for your patience and sorry for bothering you too much!

Looking forward to your updates! 

Many thanks

**Comment by NIRVANALAN** [comment]
Thanks Damian, happy mid-autumn festival too.
