### ISSUE TITLE
Release models on HF

### ISSUE THREAD

**Issue by NielsRogge** [NIRVANALAN/LN3Diff#6]
Hi @NIRVANALAN,

Niels here from the open-source team at Hugging Face. I found your work through ECCV (congrats!), the paper page is here: https://huggingface.co/papers/2403.13298, congrats on getting it accepted to ECCV (feel free to claim authorship with your HF account). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub. 

I was wondering you'd be up for collaborating on improving the release of the checkpoints on the 🤗 hub. We can add tags so that people find them when filtering https://huggingface.co/models, make sure download stats work, and leverage `safetensors` in favor of pickle.

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. In case the models are custom PyTorch model, we could probably leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to each model. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. Moreover, we can then link the checkpoints to the paper page, improving their visibility.

Let me know if you're interested/need any help regarding this!

Happy to send a PR.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by NIRVANALAN** [comment]
Hi Niels,

Thanks for contacting. I have updated my repo according to your suggestions, and now the inference & gradio can be achieved by directly loading models from hugging face.

Best regards,
Yushi

**Comment by NielsRogge** [comment]
That's great, thanks!

Btw, I saw the Spaces repo currently includes the checkpoints, usually we recommend to push the checkpoints to dedicated individual model repos, which can then be used in the Space like so:

```python
from huggingafce_hub import hf_hub_download

filepath = hf_hub_download(repo_id="yslan/LN3Diff_I23D", filename="checkpoints/objaverse/model_rec1680000.pt")
```
Model repos usually only contain the weights, rather than the entire code base.

This way, the Spaces demo and model repo will also automatically show up as being linked to each other.

**Comment by NielsRogge** [comment]
I also opened https://huggingface.co/yslan/LN3Diff/discussions/1 for a pipeline tag

**Comment by NIRVANALAN** [comment]
Thanks Niels, thanks for your message and I will revise the pipeline accordingly~
