### ISSUE TITLE
Details about views sampling

### ISSUE THREAD

**Issue by ghost** [NIRVANALAN/LN3Diff#8]
Hi, @NIRVANALAN. 

Sorry to bother you. I have an issue about view sampling, and I couldn’t find the relevant code in this repository. (transform .ply into .png, .json, etc.) Could you please provide the code or suggest any open-source works related to this process? 

Thank you for your time and assistance!

**Comment by NIRVANALAN** [comment]
Hi, thanks for your message. I am busy with ECCV conference at Milano recently, and if you have any questions, please feel free to comment and let me know.

**Comment by ghost** [comment]
Thank you very much! I read up on the rendering details of the G-buffer Objaverse and Zero 123 yesterday. This issue has been resolved. Wish you every success.
